# -*- mode: ruby -*-
# vi: set ft=ruby

# global configuration for the docker host
DOCKER_HOST_NAME = "iomdev"
DOCKER_HOST_VAGRANTFILE = "../Vagrantfile"

Vagrant.configure(2) do |config|

  # provide a private docker registry
  config.vm.define "registry", autostart: false do |container|

    container.vm.provider "docker" do |d|

      # configure the docker config
      d.image = "registry"
      d.remains_running = true
      # [host port:container port]
      d.ports = ['5000:5000']
      d.name = 'registry'

      # configure a dedicated docker host
      d.vagrant_machine = "#{DOCKER_HOST_NAME}"
      d.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
    end
  end

  # provide a dockered IOM installation
  config.vm.define "dockered-dev-iom" do |container|
    container.vm.provider "docker" do |d|

      # configure the docker config
      d.image = "jengdocker01.rnd.j.intershop.de:5000/iom-centos7-env:2.2.1.0-SNAPSHOT"
      # d.image = "10.0.15.51:5000/iom-centos7-env:2.2.1.0-SNAPSHOT"
      d.create_args = ['--privileged']
      d.remains_running = true
      # [host port:container port]
      d.ports = ['8080:8080', '9990:9990']
      # d.volumes = ['/etc/opt/oms.standalone:/etc/opt/oms.standalone']
      d.volumes = ['/home/vagrant/oms/trunk/oms.deployment/etc:/etc/opt/oms.standalone']
      d.name = '2.2.1.0-SNAPSHOT'
      d.pull = true
      # d.cmd = [
      #     "/usr/sbin/init"
      #     # ,
      #     # # wait for a running wildfly
      #     # "sleep 200",
      #     # # re-configure cluster.properties
      #     # "/bin/bash -c 'cd /opt/oms.standalone && . bin/set_env.sh && cat $OMS_ETC/cluster.properties | update_properties.sh --jboss-cli=\"jboss-cli.sh -u=$JBOSS_ADMIN_USER -p=$JBOSS_ADMIN_PASSWD -c --controller=$JBOSS_BIND_ADDRESS:$JBOSS_MGMT_PORT\"'",
      #     # # Fix for Error: Could not rename /opt/jboss/wildfly/standalone/configuration/standalone_xml_history/current
      #     # "rm -rf /opt/wildfly.standalone/standalone/configuration/standalone_xml_history",
      #     # # restart
      #     # "systemctl restart jboss-as-standalone"
      # ]

      # configure a dedicated docker host
      d.vagrant_machine = "#{DOCKER_HOST_NAME}"
      d.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
    end
  end

end
