#!/bin/bash

usage() {
    ME=$(basename $0)
    cat <<EOF
$ME
    reconfigures a dockerized IOM

SYNOPSIS
    $ME <ID>

DESCRIPTION
    Reads <ID> from command line to reconfigure a dockerized IOM
EOF
}

ID=$1

if [ -z "$ID" ]; then
    echo "ID missing!" 1>&2
    echo 1>&2
    usage 1>&2
    exit 1
fi

# Reconfigure  the IOM container
set -x
docker exec $ID bash /usr/local/bin/docker_reconfigure.sh
