#!/bin/bash

usage() {
    ME=$(basename $0)
    cat <<EOF
$ME
    creates a new dockerized DB

SYNOPSIS
    $ME <config-file>

DESCRIPTION
    Reads <config-file> to create a new dockerized DB. The name of <config-file>
    will be used as part of the ID of the newly created container: <ID>_db.
EOF
}

# returns value of requested property from cluster.properties
clusterProperty() {
    PROPERTIES_FILE="$1/cluster.properties"

    # get line containing the requested property:
    # ignore property name inside comments
    # quote all regex special chars in property name
    # if more than one line was found, last wins
    PROP_QUOTED=$(echo "$2" | sed -e 's/\./\\./g')
    LINE=$(grep "^[ \t]*/system-property=$PROP_QUOTED[ \t]*:" "$PROPERTIES_FILE" | tail -n 1)

    # extract value from line
    echo "$LINE" | sed -e 's/^[^:]*:[ \t]*"\([^"]*\).*/\1/g'
}

# $1 is name of the config-file
# check $1

CONFIG_FILE=$1

# check config-file
if [ -z "$CONFIG_FILE" -o ! -f "$CONFIG_FILE" ]; then
    echo "config-file missing!" 1>&2
    echo 1>&2
    usage 1>&2
    exit 1
fi

# check syntax of $CONFIG_FILE
if ! ( set -e; . $CONFIG_FILE ); then
    echo "error reading '$CONFIG_FILE'" 1>&2
    exit 1
fi

# read $CONFIG_FILE
. $CONFIG_FILE

# check properties
if [ -z "$ETC_DIR" -o ! -d "$ETC_DIR" ]; then
    echo "ETC_DIR is not a valid directory: '$ETC_DIR'" 1>&2
    exit 1
elif [ -z "$LOG_DIR" -o ! -d "$LOG_DIR" ]; then
    echo "LOG_DIR is not a valid directory: '$LOG_DIR'" 1>&2
    exit 1
elif [ -z "$SRC_DIR" -o ! -d "$SRC_DIR" ]; then
    echo "SRC_DIR is not a valid directory: '$SRC_DIR'" 1>&2
    exit 1
elif [ -z "$APP_DIR" -o ! -d "$APP_DIR" ]; then
    echo "$APP_DIR is not a valid directory: '$APP_DIR'" 1>&2
    exit 1
elif [ ! -z "$PGDATA_DIR" -a ! -d "$PGDATA_DIR" ]; then
    echo "PGDATA_DIR is not a valid directory: '$PGDATA_DIR'" 1>&2
    exit 1
elif [ -z "$DUMP" -o ! -f "$SRC_DIR/postgres/dumps/$DUMP" ]; then
    echo "DUMP is not a valid file in $SRC_DIR/postgres/dumps: '$DUMP'" 1>&2
    exit 1
elif [ -z "$PG_IMAGE" ]; then
    echo "PG_IMAGE must not be empty" 1>&2
    exit 1
elif [ -z "IOM_IMAGE" ]; then
    echo "IOM_IMAGE must not be empty" 1>&2
    exit 1
fi

ID=$(basename $CONFIG_FILE)

# read db-configuration from cluster.properties
POSTGRES_DB=$(clusterProperty "$ETC_DIR" "is.oms.db.name")
POSTGRES_USER=$(clusterProperty "$ETC_DIR" "is.oms.db.user")
POSTGRES_PASSWORD=$(clusterProperty "$ETC_DIR" "is.oms.db.pass")

# start the postgres database container
set -x
docker run -d \
       -e POSTGRES_DB=$POSTGRES_DB \
       -e POSTGRES_USER=$POSTGRES_USER \
       -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
       -v $LOG_DIR:/tmp/pglog \
       $( if [ ! -z "$PGDATA_DIR" ]; then echo "-v $PGDATA_DIR:/var/lib/postgresql/data"; fi ) \
       -v $SRC_DIR:/tmp/src \
       -p 5432:5432 \
       --name ${ID}_db \
       $PG_IMAGE \
       postgres -c log_directory=/tmp/pg_log -c max_prepared_transactions=10 -c logging_collector=on -c log_destination=stderr,csvlog -c log_filename=pg-VM-%Y%m%d_%H%M.log -c log_rotation_age=1h -c log_min_duration_statement=200
