kind: Pod
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: ${DOCKER_DB_IMAGE}
    args: ["-N", "500", "-c", "max_prepared_transactions=100"]
    imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      name: postgres
  type: LoadBalancer
  